apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xs3bucketiambuilders.demo.upbound.io
  labels:
    composition: role-policy
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: demo.upbound.io/v1alpha1
    kind: XS3BucketIamBuilder
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          forProvider:
            region: us-west-2
      name: s3bucket
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.region
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.tags.Name
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketOwnershipControls
        spec:
          forProvider:
            region: us-west-2
      name: s3bucket-ownership
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.region
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-ownership"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.bucket
        - fromFieldPath: spec.ownership
          toFieldPath: spec.forProvider.rule[0].objectOwnership
    - base:
        apiVersion: upbound.io/v1alpha1
        kind: XBuilder
        spec:
          compositionSelector:
            matchLabels:
              builder: iam
              cloud: aws
              service: s3
          resourceConfig:
            providerConfigName: default
          builderConfig:
            cloudParameters:
              iam:
                aws:
                  region: us-west-2
      name: s3bucket-role-policy-rpa
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.name
        - fromFieldPath: spec.builderConfig
          toFieldPath: spec.compositionSelector.matchLabels.config
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-s3-role-new-crud"