apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3builders.demo.upbound.io
spec:
  group: demo.upbound.io
  names:
    kind: XS3Builder
    plural: xs3builders
  claimNames:
    kind: S3Builder
    plural: s3builders
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Create s3 buckets
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: "id/name"
                region:
                  type: string
                  description: Region
                config:
                  type: object
                  description: Place to put additional config items
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - id
                - region