apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketOwnershipControls
metadata:
  name: crossplane-demo-changeme-ownership
  labels:
    crossplane-demo: managed-resources
spec:
  forProvider:
    bucket: crossplane-demo-changeme
    region: us-west-2
    rule:
      - objectOwnership: BucketOwnerPreferred
