apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketOwnershipControls
metadata:
  name: crossplane-demo-garreeoke-ownership
spec:
  forProvider:
    bucket: crossplane-demo-garreeoke
    region: us-west-2
    rule:
      - objectOwnership: BucketOwnerPreferred
