apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketPolicy
metadata:
  name: crossplane-demo-garreeoke
spec:
    forProvider:
      bucket: crossplane-demo-garreeoke
      region: us-west-2
      policy: |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Sid": "FullAccess",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
              "s3:GetObject",
              "s3:GetObjectAcl",
              "s3:PutObject",
              "s3:PutObjectAcl",
              "s3:DeleteObject",
              "s3:DeleteObjectTagging",
              "s3:DeleteObjectVersionTagging",
              "s3:GetObjectTagging",
              "s3:GetObjectVersionTagging",
              "s3:PutObjectTagging",
              "s3:PutObjectVersionTagging"
            ],
            "Resource": [
              "arn:aws:s3:::crossplane-demo-garreeoke/*"
            ]
          }]
        }