apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: crossplane-demo-changeme-s3-crud
  labels:
    role: crossplane-demo-changeme-s3-iam-role
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
          },
          {
            "Effect":"Allow",
            "Action":["s3:ListBucket","s3:GetBucketLocation"],
            "Resource":"arn:aws:s3:::crossplane-demo-changeme"
          },
          {
            "Effect": "Allow",
            "Action": [
              "s3:PutObject",
              "s3:PutObjectAcl",
              "s3:GetObject",
              "s3:GetObjectVersion",
              "s3:GetObjectAcl",
              "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::crossplane-demo-changeme/*"
          }
        ]
      }