apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3-bucket-role-policy.demo.upbound.io
  labels:
    composition: role-policy
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: demo.upbound.io/v1alpha1
    kind: XS3Builder
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          forProvider:
            region: us-west-2
      name: s3bucket
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.region
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.tags.Name
    - base:
        apiVersion: cfg.upbound.io/v1alpha1
        kind: XIam
        spec:
          cloud: aws
          cloudService: s3
          resourceConfig:
            providerConfigName: default
          cloudParameters:
            aws:
              region: us-west-2
      name: s3bucket-policy
      patches:
        - fromFieldPath: spec.config.iamConfig
          toFieldPath: spec.config
        - fromFieldPath: spec.i
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-s3-role-new-crud-ibp"
        - fromFieldPath: spec.id
          toFieldPath: spec.name