apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xs3owners.demo.upbound.io
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: demo.upbound.io/v1alpha1
    kind: XS3Owner
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          forProvider:
            region: us-west-1
      name: s3bucket
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.region
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.tags.Name
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketOwnershipControls
        spec:
          forProvider:
            region: us-west-1
      name: s3bucket-ownership
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.region
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.bucket
        - fromFieldPath: spec.ownership
          toFieldPath: spec.forProvider.rule[0].objectOwnership
        
        